---
- name: Initialize and format disk on Windows VM
  hosts: windows
  tasks:
    - name: Initialize disk
      ansible.windows.win_shell: |
        Initialize-Disk -Number "{{ DiskNumber }}" | Set-Disk -IsOffline $false
        New-Partition -DiskNumber "{{ DiskNumber }}" -DriveLetter "{{ DriveLetter }}" -UseMaximumSize
        Format-Volume -DriveLetter "{{ DriveLetter }} -NewFileSystemLabel "{{ DriveName }}"
