---
- name: Initialize and format uninitialized disks
  hosts: windows
  tasks:
    - name: Gather disk facts
      win_disk_facts:

    - name: Identify uninitialized disks
      set_fact:
        uninitialized_disks: "{{ disk_facts.disks | selectattr('partition_style', 'equalto', 'raw') | list }}"
      vars:
        disk_facts: "{{ ansible_facts['disks'] }}"

    - name: Initialize uninitialized disks
      win_disk:
        disk_number: "{{ item.number }}"
        partition_style: gpt
      loop: "{{ uninitialized_disks }}"
      when: uninitialized_disks | length > 0

    - name: Create partitions and format disks
      win_partition:
        disk_number: "{{ item.number }}"
        drive_letter: "{{ item.letter | default('E') }}"  # Default to E if no preference
        partition_size: "{{ item.size | default('100%') }}"
        file_system: NTFS
      loop: "{{ uninitialized_disks }}"
      when: uninitialized_disks | length > 0

    - name: Display success message
      debug:
        msg: "Disk initialization and formatting completed for disks: {{ uninitialized_disks | map(attribute='number') | join(', ') }}"
      when: uninitialized_disks | length > 0
