---
- name: Initialize and format disk on Windows VM
  hosts: windows
  tasks:
    - name: Initialize disk
      ansible.windows.win_shell: |
        Initialize-Disk -Number 1 | Set-Disk -IsOffline $false
        New-Partition -DiskNumber 1 -DriveLetter E -UseMaximumSize
