---
- name: Change user password on Windows
  hosts: all
  tasks:
    - name: Change the password for a user
      win_user:
        name: win_username       # Replace with the actual username
        password: win_password  # Replace with the new password
        update_password: always # Ensures the password is updated
